extends:
  - '@antfu'
plugins:
  - eslint-plugin-tsdoc
rules:
  tsdoc/syntax: warn
  no-cond-assign: warn
  # curly: [error, multi, consistent]
  curly: [error, multi-line]
  max-statements-per-line: off
  brace-style: [error, 1tbs, {allowSingleLine: true}]
  '@typescript-eslint/brace-style': off
  '@typescript-eslint/comma-dangle': off
