name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install pnpm
      run: npm i -g pnpm
    - name: Install deps
      run: pnpm i
    - run : pnpm ci --ignore-scripts
    - run : pnpm run docs
    - name: Make GitHub links absolute
      run :
        shopt -s globstar;
        sed
          --in-place
          --expression='s:/develop/docs/:/${{ github.sha }}/docs/:g'
          --expression='s:<img src="docs/assets/:<img src="media/:g'
          web/**/*.html;
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          # for v3.html and perhaps CNAME
          keep_files: true
    - name: Publish to npm
      run : |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts
      env :
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
